In [1]:
import numpy as np

from photutils import CircularAperture
from photutils import CircularAnnulus
from photutils import aperture_photometry
from astropy.io import fits

import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
from astropy.stats import mad_std

import pandas as pd
from statistics import stdev

In [75]:
# Star one average count and stdev

data = pd.read_csv('star_1.csv')

s1_mag = [16.262, 16.023, 15.935, 15.936]

df1 = data.query('Filter == "g"')
g_c = df1['Source Counts']
avg_g = round(np.average(g_c)  ,5)  
sys_g = round(stdev(g_c),5)
C_g1 =  round(s1_mag[0]+ 2.5*np.log10(g_c/90), 3) 

df1 = data.query('Filter == "r"')
r_c = df1['Source Counts']
avg_r = round(np.average(r_c), 5) 
sys_r = round(stdev(r_c),5)
C_r1 =  round(s1_mag[1]+ 2.5*np.log10(r_c/90), 3) 

df1 = data.query('Filter == "i"')    
i_c = df1['Source Counts']
avg_i = round(np.average(i_c) ,5)
sys_i = round(stdev(i_c),5)
C_i1 =  round(s1_mag[2]+ 2.5*np.log10(i_c/90), 3) 

df1 = data.query('Filter == "z"')    
z_c = df1['Source Counts']
avg_z = round(np.average(z_c) ,5)
sys_z = round(stdev(z_c),5)
C_z1 =  round(s1_mag[3]+ 2.5*np.log10(z_c/90), 3) 

avg_n1 = [avg_g, avg_r, avg_i, avg_z]
sys_n1 = [sys_g, sys_r, sys_i, sys_z] 
C_g1_dev = round(stdev(C_g1), 5)
C_r1_dev = round(stdev(C_r1), 5)
C_i1_dev = round(stdev(C_i1), 5)
C_z1_dev = round(stdev(C_z1), 5)

C1=[0,0,0,0]
C1_sig=[C_g1_dev, C_r1_dev, C_i1_dev, C_z1_dev]
for j in range(0,4):
    C1[j-1] =  round(s1_mag[j]+ 2.5*np.log10(avg_n1[j]/90), 3)    
C_prop = 1/avg_g*1/np.log(10)*sys_g
print(C1)
print(sys_n1)
print(C1_sig)
print(avg_n1)
print(C_prop)

[25.118, 25.071, 25.071, 25.072]
[3611.21922, 4720.55221, 8403.88451, 5999.77082]
[0.01311, 0.01332, 0.02257, 0.01602]
[300787.10499, 390921.00015, 405963.36717, 405876.86513]
0.005214095132971561


In [73]:
data = pd.read_csv('star_2.csv')

s2_mag = [17.806, 16.459, 15.850, 15.524]

df2 = data.query('Filter == "g"')
g_c = df2['Source Counts']
avg_g = round(np.average(g_c)  ,5)  
sys_g = round(stdev(g_c),5)
C_g2 =  round(s2_mag[0]+ 2.5*np.log10(g_c/90), 3) 

df2 = data.query('Filter == "r"')
r_c = df2['Source Counts']
avg_r = round(np.average(r_c), 5) 
sys_r = round(stdev(r_c),5)
C_r2 =  round(s2_mag[1]+ 2.5*np.log10(r_c/90), 3) 

df2 = data.query('Filter == "i"')    
i_c = df2['Source Counts']
avg_i = round(np.average(i_c) ,5)
sys_i = round(stdev(i_c),5)
C_i2 =  round(s2_mag[2]+ 2.5*np.log10(i_c/90), 3) 

df2 = data.query('Filter == "z"')    
z_c = df2['Source Counts']
avg_z = round(np.average(z_c) ,5)
sys_z = round(stdev(z_c),5)
C_z2 =  round(s2_mag[3]+ 2.5*np.log10(z_c/90), 3)

avg_n2 = [avg_g, avg_r, avg_i, avg_z]
sys_n2 = [sys_g, sys_r, sys_i, sys_z] 
C_g2_dev = round(stdev(C_g2), 5)
C_r2_dev = round(stdev(C_r2), 5)
C_i2_dev = round(stdev(C_i2), 5)
C_z2_dev = round(stdev(C_z2), 5)

C2_sig=[C_g2_dev, C_r2_dev, C_i2_dev, C_z2_dev]

C2=[0,0,0,0]

for i in range(0,4):
    C2[i-1] =  round(s2_mag[i]+ 2.5*np.log10(avg_n2[i]/90), 3)

print(C2) 
print(sys_n2)
print(C2_sig)
print(avg_n2)

[25.186, 25.166, 25.101, 25.191]
[3315.05857, 4476.80689, 2316.68208, 3691.92419]
[0.04447, 0.01759, 0.00497, 0.0066]
[80931.17825, 278681.88962, 479358.54251, 609596.11428]


In [4]:
# Averaging Cs
C12 = [C1,C2]
print(C12)
C12_sig = C1_sig, C2_sig

C = np.mean(C12, axis = 0) #averages the columns with axis = 0
C_sig = np.mean(C12_sig, axis = 0)
print(C)
print(C_sig)


[[25.118, 25.071, 25.071, 25.072], [25.186, 25.166, 25.101, 25.191]]
[25.152  25.1185 25.086  25.1315]
[0.02879  0.015455 0.01377  0.01131 ]


In [6]:
def tp(data):
    d = np.transpose(data)
    print(d)
    return d


#C_table = pd.DataFrame(Cs, columns = ['Star 1', 'Star 2', 'Average C', 'Sigma C'], index = ['g', 'r', 'i', 'z'],)
#print(C_table)
#.to_csv('C-table.csv', index=None, sep=',', mode='w') 

In [5]:
a = C.tolist()
b = C_sig.tolist()

Cs = C1, C2, a, b
print(Cs)



([25.118, 25.071, 25.071, 25.072], [25.186, 25.166, 25.101, 25.191], [25.152, 25.1185, 25.086, 25.1315], [0.028790000000000003, 0.015455, 0.01377, 0.01131])


In [7]:
cs2 = tp(Cs)
print(cs2)



[[2.51180e+01 2.51860e+01 2.51520e+01 2.87900e-02]
 [2.50710e+01 2.51660e+01 2.51185e+01 1.54550e-02]
 [2.50710e+01 2.51010e+01 2.50860e+01 1.37700e-02]
 [2.50720e+01 2.51910e+01 2.51315e+01 1.13100e-02]]
[[2.51180e+01 2.51860e+01 2.51520e+01 2.87900e-02]
 [2.50710e+01 2.51660e+01 2.51185e+01 1.54550e-02]
 [2.50710e+01 2.51010e+01 2.50860e+01 1.37700e-02]
 [2.50720e+01 2.51910e+01 2.51315e+01 1.13100e-02]]


In [15]:
df = pd.DataFrame(data = None,  index = ('g', 'r', 'i', 'z'), columns = ('Star 1', 'Star 2', 'Average C', 'Sigma C'))
print(df)


  Star 1 Star 2 Average C Sigma C
g    NaN    NaN       NaN     NaN
r    NaN    NaN       NaN     NaN
i    NaN    NaN       NaN     NaN
z    NaN    NaN       NaN     NaN


In [17]:
df['Star 1']= C1
df['Star 2']= C2
df['Average C']= C
df['Sigma C']= C_sig
print(df)


   Star 1  Star 2  Average C   Sigma C
g  25.118  25.186    25.1520  0.028790
r  25.071  25.166    25.1185  0.015455
i  25.071  25.101    25.0860  0.013770
z  25.072  25.191    25.1315  0.011310


In [18]:
df.to_csv('C-table.csv', sep=',', mode='w') 

In [19]:
# Finding band difs and standard deviations

band_dif = [0,0,0]
avg_n = [0,0,0]
sys_n = [0,0,0]
for j in range(0,3):
    x = j+3
    o = "star_%d.csv"%x
    data = pd.read_csv(o)    
    
    df3 = data.query('Filter == "g"')
    g_c = df3['Source Counts']
    avg_g = round(np.average(g_c)  ,5)  
    sys_g = round(stdev(g_c),5)    

    df3 = data.query('Filter == "r"')
    r_c = df3['Source Counts']
    avg_r = round(np.average(r_c), 5) 
    sys_r = round(stdev(r_c),5)

    df3 = data.query('Filter == "i"')    
    i_c = df3['Source Counts']
    avg_i = round(np.average(i_c) ,5)
    sys_i = round(stdev(i_c),5)

    df3 = data.query('Filter == "z"')    
    z_c = df3['Source Counts']
    avg_z = round(np.average(z_c) ,5)
    sys_z = round(stdev(z_c),5)

    avg_n[j] = [avg_g, avg_r, avg_i, avg_z]
    sys_n[j] = [sys_g, sys_r, sys_i, sys_z]    


counts = pd.DataFrame(avg_n, columns= ['g', 'r', 'i', 'z'])
st_dev = pd.DataFrame(sys_n, columns= ['g', 'r', 'i', 'z'])
print(counts)
print(st_dev)

              g             r             i             z
0  210161.37086  363686.61350  430755.86322  474594.47393
1   65351.40363  251072.04506  458410.30451  604049.55616
2  328027.31691  407249.71000  410773.21577  398684.04845
            g           r           i            z
0  3424.48505  4914.15159  3092.51214   4124.87895
1  3180.83428  3413.96973  6238.74015  10107.93382
2  5713.86384  4215.36411  8807.44864   5731.60254


In [ ]:
counts.to_csv('final_counts.csv', index=None, sep=',', mode='w') 
st_dev.to_csv('final_count_errors.csv', index=None, sep=',', mode='w') 

In [20]:
def get_mag(band):
    m = -2.5*np.log10(band/90)
    return m
pre_mag = counts.applymap(get_mag)
#print(pre_mag)
mag = pre_mag + C
print(mag)


           g          r          i          z
0  16.731224  16.102288  15.886028  15.826300
1  17.999469  16.504610  15.818470  15.564425
2  16.247831  15.979454  15.937601  16.015534


In [ ]:
mag.to_csv('final_mags.csv', index=None, sep=',', mode='w') 

In [21]:
# sigma magnitude
x = np.log(10)
#y = counts/90
sigma_mag =  np.sqrt((2.5*st_dev/(counts*x))**2+C_sig**2)
print(sigma_mag)


          g         r         i         z
0  0.033791  0.021309  0.015823  0.014730
1  0.060179  0.021373  0.020198  0.021401
2  0.034446  0.019109  0.027047  0.019276


In [ ]:
sigma_mag.to_csv('final_mags_error.csv', index=None, sep=',', mode='w') 

In [22]:
m = mag
band_difs=pd.DataFrame()
band_difs['B-V'] = 0.98*(m['g']-m['r'])  + 0.22
#band_difs['V-R'] = 1.09*(m['r']-m['i']) + 0.22
band_difs['R-I'] = 1*(m['r']-m['i']) + 0.21
#band_difs['B'] = m['g'] + 0.39*(m['g']-m['r']) + 0.21
band_difs['V'] = m['g'] - 0.59*(m['g']-m['r']) -0.01

print(band_difs)

        B-V       R-I          V
0  0.836357  0.426260  16.350152
1  1.684961  0.896140  17.107502
2  0.483009  0.251853  16.079489


In [23]:
sigma_dif = pd.DataFrame()
sigma_dif['B-V'] = np.sqrt(0.98**2*(sigma_mag['g']**2 + sigma_mag['r']**2))
#sigma_dif['V-R'] = np.sqrt(1.09**2*(sigma_mag['r']**2 + sigma_mag['i']**2))
sigma_dif['R-I'] = np.sqrt(sigma_mag['r']**2 + sigma_mag['i']**2)
sigma_dif['V'] = np.sqrt((sigma_mag['g']**2)*(1-0.59)**2 + (.59**2)*sigma_mag['r']**2)
print(sigma_dif)

        B-V       R-I         V
0  0.039150  0.026542  0.018709
1  0.062585  0.029407  0.027709
2  0.038604  0.033116  0.018071


In [24]:
# this is to get a range with standard deviation
bd_l = band_difs-sigma_dif
bd_h = band_difs+sigma_dif

print(bd_l)
print(bd_h)

        B-V       R-I          V
0  0.797207  0.399718  16.331443
1  1.622377  0.866733  17.079793
2  0.444406  0.218737  16.061418
        B-V       R-I          V
0  0.875508  0.452801  16.368860
1  1.747546  0.925547  17.135212
2  0.521613  0.284970  16.097560


In [ ]:
band_difs.to_csv('band-difs.csv', index=None, sep=',', mode='w') 
sigma_dif.to_csv('band-dif-errors.csv', index=None, sep=',', mode='w') 
#df.to_csv('star_5.csv', index=None, sep=',', mode='w') 

In [ ]:
print("Star 3: Main Sequence K0")
print("Star 4: Supergiant, K5")
print("Star 5: Main sequence, F5")

In [25]:
def distance(V, M):
    d = 10**((V-M)/5+1)
    return d
M = [5.9,-5.8,3.5]             

In [26]:
d = distance(band_difs['V'], M)
print(d)


0      1230.354759
1    381505.215871
2      3280.180716
Name: V, dtype: float64


In [33]:
# Star one average count and stdev

data = pd.read_csv('star_1.csv')
df1 = data.filter(['Filter','Stat error: N'])


g_c = df1.query('Filter == "g"')
avg_g = round(np.average(g_c['Stat error: N'])  ,2) 

r_c = df1.query('Filter == "r"')
avg_r = round(np.average(r_c['Stat error: N']), 2) 

i_c = df1.query('Filter == "i"')
avg_i = round(np.average(i_c['Stat error: N']) ,2)


z_c = df1.query('Filter == "z"')
avg_z = round(np.average(z_c['Stat error: N']) ,2)

avg_n1 = [avg_g, avg_r, avg_i, avg_z]




print(avg_n1)


[716.77, 776.13, 788.77, 786.52]


In [48]:
sig_d1 = band_difs['V']/sigma_dif['V']
print(sig_d1)

0    873.937759
1    617.394903
2    889.786063
Name: V, dtype: float64


In [43]:
sig_d2 = np.sqrt(d)
print(sig_d2)

0     35.076413
1    617.661085
2     57.272862
Name: V, dtype: float64


In [44]:
sig_d3 = np.sqrt((2*np.log(10))**2*(10**((band_difs['V']-M)/5))**2*data['V']**2)
print(sig_d3)

0      10.600280
1    4868.214821
2      27.297954
Name: V, dtype: float64


In [67]:
sig_d4 = np.sqrt((2*np.log(10))**2*(10**((band_difs['V']-M)/5))**2*sigma_dif['V']**2+(((-2*np.log(10))*(10**((band_difs['V']-M)/5)))**2))
print(sig_d4)

0       566.698455
1    175757.078756
2      1510.825677
Name: V, dtype: float64


In [71]:
sig_d5 = np.sqrt(10**((band_difs['V']-M)/5)**2*(((np.log(10**2))*sigma_dif['V'])**2+(np.log(10**-2))**2))
d5 = round(sig_d5, 2)
print(sig_d5)
print(d5)

0    7.037771e+02
1    1.440408e+11
2    6.732671e+03
Name: V, dtype: float64
0    7.037800e+02
1    1.440408e+11
2    6.732670e+03
Name: V, dtype: float64
